apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cafe-admin

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - identity-service.yaml
  - catalog-service.yaml
  - floor-service.yaml
  - ordering-service.yaml
  - billing-service.yaml
  - reporting-service.yaml
  - api-gateway.yaml
